const countryCodesIndexed = [
  {
    AF: { name: "Afghanistan", dial_code: "+93", code: "AF", emoji: "🇦🇫" },
    AX: { name: "Aland Islands", dial_code: "+358", code: "AX", emoji: "🇦🇽" },
    AL: { name: "Albania", dial_code: "+355", code: "AL", emoji: "🇦🇱" },
    DZ: { name: "Algeria", dial_code: "+213", code: "DZ", emoji: "🇩🇿" },
    AS: { name: "American Samoa", dial_code: "+1684", code: "AS", emoji: "🇦🇸" },
    AD: { name: "Andorra", dial_code: "+376", code: "AD", emoji: "🇦🇩" },
    AO: { name: "Angola", dial_code: "+244", code: "AO", emoji: "🇦🇴" },
    AI: { name: "Anguilla", dial_code: "+1264", code: "AI", emoji: "🇦🇮" },
    AQ: { name: "Antarctica", dial_code: "+672", code: "AQ", emoji: "🇦🇶" },
    AG: {
      name: "Antigua and Barbuda",
      dial_code: "+1268",
      code: "AG",
      emoji: "🇦🇬"
    },
    AR: { name: "Argentina", dial_code: "+54", code: "AR", emoji: "🇦🇷" },
    AM: { name: "Armenia", dial_code: "+374", code: "AM", emoji: "🇦🇲" },
    AW: { name: "Aruba", dial_code: "+297", code: "AW", emoji: "🇦🇼" },
    AU: { name: "Australia", dial_code: "+61", code: "AU", emoji: "🇦🇺" },
    AT: { name: "Austria", dial_code: "+43", code: "AT", emoji: "🇦🇹" },
    AZ: { name: "Azerbaijan", dial_code: "+994", code: "AZ", emoji: "🇦🇿" },
    BS: { name: "Bahamas", dial_code: "+1242", code: "BS", emoji: "🇧🇸" },
    BH: { name: "Bahrain", dial_code: "+973", code: "BH", emoji: "🇧🇭" },
    BD: { name: "Bangladesh", dial_code: "+880", code: "BD", emoji: "🇧🇩" },
    BB: { name: "Barbados", dial_code: "+1246", code: "BB", emoji: "🇧🇧" },
    BY: { name: "Belarus", dial_code: "+375", code: "BY", emoji: "🇧🇾" },
    BE: { name: "Belgium", dial_code: "+32", code: "BE", emoji: "🇧🇪" },
    BZ: { name: "Belize", dial_code: "+501", code: "BZ", emoji: "🇧🇿" },
    BJ: { name: "Benin", dial_code: "+229", code: "BJ", emoji: "🇧🇯" },
    BM: { name: "Bermuda", dial_code: "+1441", code: "BM", emoji: "🇧🇲" },
    BT: { name: "Bhutan", dial_code: "+975", code: "BT", emoji: "🇧🇹" },
    BO: {
      name: "Bolivia, Plurinational State of",
      dial_code: "+591",
      code: "BO",
      emoji: "🇧🇴"
    },
    BA: {
      name: "Bosnia and Herzegovina",
      dial_code: "+387",
      code: "BA",
      emoji: "🇧🇦"
    },
    BW: { name: "Botswana", dial_code: "+267", code: "BW", emoji: "🇧🇼" },
    BR: { name: "Brazil", dial_code: "+55", code: "BR", emoji: "🇧🇷" },
    IO: {
      name: "British Indian Ocean Territory",
      dial_code: "+246",
      code: "IO",
      emoji: "🇮🇴"
    },
    BN: {
      name: "Brunei Darussalam",
      dial_code: "+673",
      code: "BN",
      emoji: "🇧🇳"
    },
    BG: { name: "Bulgaria", dial_code: "+359", code: "BG", emoji: "🇧🇬" },
    BF: { name: "Burkina Faso", dial_code: "+226", code: "BF", emoji: "🇧🇫" },
    BI: { name: "Burundi", dial_code: "+257", code: "BI", emoji: "🇧🇮" },
    KH: { name: "Cambodia", dial_code: "+855", code: "KH", emoji: "🇰🇭" },
    CM: { name: "Cameroon", dial_code: "+237", code: "CM", emoji: "🇨🇲" },
    CA: { name: "Canada", dial_code: "+1", code: "CA", emoji: "🇨🇦" },
    CV: { name: "Cape Verde", dial_code: "+238", code: "CV", emoji: "🇨🇻" },
    KY: { name: "Cayman Islands", dial_code: "+ 345", code: "KY", emoji: "🇰🇾" },
    CF: {
      name: "Central African Republic",
      dial_code: "+236",
      code: "CF",
      emoji: "🇨🇫"
    },
    TD: { name: "Chad", dial_code: "+235", code: "TD", emoji: "🇹🇩" },
    CL: { name: "Chile", dial_code: "+56", code: "CL", emoji: "🇨🇱" },
    CN: { name: "China", dial_code: "+86", code: "CN", emoji: "🇨🇳" },
    CX: { name: "Christmas Island", dial_code: "+61", code: "CX", emoji: "🇨🇽" },
    CC: {
      name: "Cocos (Keeling) Islands",
      dial_code: "+61",
      code: "CC",
      emoji: "🇨🇨"
    },
    CO: { name: "Colombia", dial_code: "+57", code: "CO", emoji: "🇨🇴" },
    KM: { name: "Comoros", dial_code: "+269", code: "KM", emoji: "🇰🇲" },
    CG: { name: "Congo", dial_code: "+242", code: "CG", emoji: "🇨🇬" },
    CD: {
      name: "Congo, The Democratic Republic of the Congo",
      dial_code: "+243",
      code: "CD",
      emoji: "🇨🇩"
    },
    CK: { name: "Cook Islands", dial_code: "+682", code: "CK", emoji: "🇨🇰" },
    CR: { name: "Costa Rica", dial_code: "+506", code: "CR", emoji: "🇨🇷" },
    CI: { name: "Cote d'Ivoire", dial_code: "+225", code: "CI", emoji: "🇨🇮" },
    HR: { name: "Croatia", dial_code: "+385", code: "HR", emoji: "🇭🇷" },
    CU: { name: "Cuba", dial_code: "+53", code: "CU", emoji: "🇨🇺" },
    CY: { name: "Cyprus", dial_code: "+357", code: "CY", emoji: "🇨🇾" },
    CZ: { name: "Czech Republic", dial_code: "+420", code: "CZ", emoji: "🇨🇿" },
    DK: { name: "Denmark", dial_code: "+45", code: "DK", emoji: "🇩🇰" },
    DJ: { name: "Djibouti", dial_code: "+253", code: "DJ", emoji: "🇩🇯" },
    DM: { name: "Dominica", dial_code: "+1767", code: "DM", emoji: "🇩🇲" },
    DO: {
      name: "Dominican Republic",
      dial_code: "+1849",
      code: "DO",
      emoji: "🇩🇴"
    },
    EC: { name: "Ecuador", dial_code: "+593", code: "EC", emoji: "🇪🇨" },
    EG: { name: "Egypt", dial_code: "+20", code: "EG", emoji: "🇪🇬" },
    SV: { name: "El Salvador", dial_code: "+503", code: "SV", emoji: "🇸🇻" },
    GQ: {
      name: "Equatorial Guinea",
      dial_code: "+240",
      code: "GQ",
      emoji: "🇬🇶"
    },
    ER: { name: "Eritrea", dial_code: "+291", code: "ER", emoji: "🇪🇷" },
    EE: { name: "Estonia", dial_code: "+372", code: "EE", emoji: "🇪🇪" },
    ET: { name: "Ethiopia", dial_code: "+251", code: "ET", emoji: "🇪🇹" },
    FK: {
      name: "Falkland Islands (Malvinas)",
      dial_code: "+500",
      code: "FK",
      emoji: "🇫🇰"
    },
    FO: { name: "Faroe Islands", dial_code: "+298", code: "FO", emoji: "🇫🇴" },
    FJ: { name: "Fiji", dial_code: "+679", code: "FJ", emoji: "🇫🇯" },
    FI: { name: "Finland", dial_code: "+358", code: "FI", emoji: "🇫🇮" },
    FR: { name: "France", dial_code: "+33", code: "FR", emoji: "🇫🇷" },
    GF: { name: "French Guiana", dial_code: "+594", code: "GF", emoji: "🇬🇫" },
    PF: {
      name: "French Polynesia",
      dial_code: "+689",
      code: "PF",
      emoji: "🇵🇫"
    },
    GA: { name: "Gabon", dial_code: "+241", code: "GA", emoji: "🇬🇦" },
    GM: { name: "Gambia", dial_code: "+220", code: "GM", emoji: "🇬🇲" },
    GE: { name: "Georgia", dial_code: "+995", code: "GE", emoji: "🇬🇪" },
    DE: { name: "Germany", dial_code: "+49", code: "DE", emoji: "🇩🇪" },
    GH: { name: "Ghana", dial_code: "+233", code: "GH", emoji: "🇬🇭" },
    GI: { name: "Gibraltar", dial_code: "+350", code: "GI", emoji: "🇬🇮" },
    GR: { name: "Greece", dial_code: "+30", code: "GR", emoji: "🇬🇷" },
    GL: { name: "Greenland", dial_code: "+299", code: "GL", emoji: "🇬🇱" },
    GD: { name: "Grenada", dial_code: "+1473", code: "GD", emoji: "🇬🇩" },
    GP: { name: "Guadeloupe", dial_code: "+590", code: "GP", emoji: "🇬🇵" },
    GU: { name: "Guam", dial_code: "+1671", code: "GU", emoji: "🇬🇺" },
    GT: { name: "Guatemala", dial_code: "+502", code: "GT", emoji: "🇬🇹" },
    GG: { name: "Guernsey", dial_code: "+44", code: "GG", emoji: "🇬🇬" },
    GN: { name: "Guinea", dial_code: "+224", code: "GN", emoji: "🇬🇳" },
    GW: { name: "Guinea-Bissau", dial_code: "+245", code: "GW", emoji: "🇬🇼" },
    GY: { name: "Guyana", dial_code: "+595", code: "GY", emoji: "🇬🇾" },
    HT: { name: "Haiti", dial_code: "+509", code: "HT", emoji: "🇭🇹" },
    VA: {
      name: "Holy See (Vatican City State)",
      dial_code: "+379",
      code: "VA",
      emoji: "🇻🇦"
    },
    HN: { name: "Honduras", dial_code: "+504", code: "HN", emoji: "🇭🇳" },
    HK: { name: "Hong Kong", dial_code: "+852", code: "HK", emoji: "🇭🇰" },
    HU: { name: "Hungary", dial_code: "+36", code: "HU", emoji: "🇭🇺" },
    IS: { name: "Iceland", dial_code: "+354", code: "IS", emoji: "🇮🇸" },
    IN: { name: "India", dial_code: "+91", code: "IN", emoji: "🇮🇳" },
    ID: { name: "Indonesia", dial_code: "+62", code: "ID", emoji: "🇮🇩" },
    IR: {
      name: "Iran, Islamic Republic of Persian Gulf",
      dial_code: "+98",
      code: "IR",
      emoji: "🇮🇷"
    },
    IQ: { name: "Iraq", dial_code: "+964", code: "IQ", emoji: "🇮🇶" },
    IE: { name: "Ireland", dial_code: "+353", code: "IE", emoji: "🇮🇪" },
    IM: { name: "Isle of Man", dial_code: "+44", code: "IM", emoji: "🇮🇲" },
    IL: { name: "Israel", dial_code: "+972", code: "IL", emoji: "🇮🇱" },
    IT: { name: "Italy", dial_code: "+39", code: "IT", emoji: "🇮🇹" },
    JM: { name: "Jamaica", dial_code: "+1876", code: "JM", emoji: "🇯🇲" },
    JP: { name: "Japan", dial_code: "+81", code: "JP", emoji: "🗾" },
    JE: { name: "Jersey", dial_code: "+44", code: "JE", emoji: "🇯🇪" },
    JO: { name: "Jordan", dial_code: "+962", code: "JO", emoji: "🇯🇴" },
    KZ: { name: "Kazakhstan", dial_code: "+77", code: "KZ", emoji: "🇰🇿" },
    KE: { name: "Kenya", dial_code: "+254", code: "KE", emoji: "🇰🇪" },
    KI: { name: "Kiribati", dial_code: "+686", code: "KI", emoji: "🇰🇮" },
    KP: {
      name: "Korea, Democratic People's Republic of Korea",
      dial_code: "+850",
      code: "KP",
      emoji: "🇰🇵"
    },
    KR: {
      name: "Korea, Republic of South Korea",
      dial_code: "+82",
      code: "KR",
      emoji: "🇰🇷"
    },
    KW: { name: "Kuwait", dial_code: "+965", code: "KW", emoji: "🇰🇼" },
    KG: { name: "Kyrgyzstan", dial_code: "+996", code: "KG", emoji: "🇰🇬" },
    LA: { name: "Laos", dial_code: "+856", code: "LA", emoji: "🇱🇦" },
    LV: { name: "Latvia", dial_code: "+371", code: "LV", emoji: "🇱🇻" },
    LB: { name: "Lebanon", dial_code: "+961", code: "LB", emoji: "🇱🇧" },
    LS: { name: "Lesotho", dial_code: "+266", code: "LS", emoji: "🇱🇸" },
    LR: { name: "Liberia", dial_code: "+231", code: "LR", emoji: "🇱🇷" },
    LY: {
      name: "Libyan Arab Jamahiriya",
      dial_code: "+218",
      code: "LY",
      emoji: "🇱🇾"
    },
    LI: { name: "Liechtenstein", dial_code: "+423", code: "LI", emoji: "🇱🇮" },
    LT: { name: "Lithuania", dial_code: "+370", code: "LT", emoji: "🇱🇹" },
    LU: { name: "Luxembourg", dial_code: "+352", code: "LU", emoji: "🇱🇺" },
    MO: { name: "Macao", dial_code: "+853", code: "MO", emoji: "🇲🇴" },
    MK: { name: "Macedonia", dial_code: "+389", code: "MK", emoji: "🇲🇰" },
    MG: { name: "Madagascar", dial_code: "+261", code: "MG", emoji: "🇲🇬" },
    MW: { name: "Malawi", dial_code: "+265", code: "MW", emoji: "🇲🇼" },
    MY: { name: "Malaysia", dial_code: "+60", code: "MY", emoji: "🇲🇾" },
    MV: { name: "Maldives", dial_code: "+960", code: "MV", emoji: "🇲🇻" },
    ML: { name: "Mali", dial_code: "+223", code: "ML", emoji: "🇲🇱" },
    MT: { name: "Malta", dial_code: "+356", code: "MT", emoji: "🇲🇹" },
    MH: {
      name: "Marshall Islands",
      dial_code: "+692",
      code: "MH",
      emoji: "🇲🇭"
    },
    MQ: { name: "Martinique", dial_code: "+596", code: "MQ", emoji: "🇲🇶" },
    MR: { name: "Mauritania", dial_code: "+222", code: "MR", emoji: "🇲🇷" },
    MU: { name: "Mauritius", dial_code: "+230", code: "MU", emoji: "🇲🇺" },
    YT: { name: "Mayotte", dial_code: "+262", code: "YT", emoji: "🇾🇹" },
    MX: { name: "Mexico", dial_code: "+52", code: "MX", emoji: "🇲🇽" },
    FM: {
      name: "Micronesia, Federated States of Micronesia",
      dial_code: "+691",
      code: "FM",
      emoji: "🇫🇲"
    },
    MD: { name: "Moldova", dial_code: "+373", code: "MD", emoji: "🇲🇩" },
    MC: { name: "Monaco", dial_code: "+377", code: "MC", emoji: "🇲🇨" },
    MN: { name: "Mongolia", dial_code: "+976", code: "MN", emoji: "🇲🇳" },
    ME: { name: "Montenegro", dial_code: "+382", code: "ME", emoji: "🇲🇪" },
    MS: { name: "Montserrat", dial_code: "+1664", code: "MS", emoji: "🇲🇸" },
    MA: { name: "Morocco", dial_code: "+212", code: "MA", emoji: "🇲🇦" },
    MZ: { name: "Mozambique", dial_code: "+258", code: "MZ", emoji: "🇲🇿" },
    MM: { name: "Myanmar", dial_code: "+95", code: "MM", emoji: "🇲🇲" },
    NA: { name: "Namibia", dial_code: "+264", code: "NA", emoji: "🇳🇦" },
    NR: { name: "Nauru", dial_code: "+674", code: "NR", emoji: "🇳🇷" },
    NP: { name: "Nepal", dial_code: "+977", code: "NP", emoji: "🇳🇵" },
    NL: { name: "Netherlands", dial_code: "+31", code: "NL", emoji: "🇳🇱" },
    AN: {
      name: "Netherlands Antilles",
      dial_code: "+599",
      code: "AN",
      emoji: "🇳🇱"
    },
    NC: { name: "New Caledonia", dial_code: "+687", code: "NC", emoji: "🇳🇨" },
    NZ: { name: "New Zealand", dial_code: "+64", code: "NZ", emoji: "🇳🇿" },
    NI: { name: "Nicaragua", dial_code: "+505", code: "NI", emoji: "🇳🇮" },
    NE: { name: "Niger", dial_code: "+227", code: "NE", emoji: "🇳🇪" },
    NG: { name: "Nigeria", dial_code: "+234", code: "NG", emoji: "🇳🇬" },
    NU: { name: "Niue", dial_code: "+683", code: "NU", emoji: "🇳🇺" },
    NF: { name: "Norfolk Island", dial_code: "+672", code: "NF", emoji: "🇳🇫" },
    MP: {
      name: "Northern Mariana Islands",
      dial_code: "+1670",
      code: "MP",
      emoji: "🇲🇵"
    },
    NO: { name: "Norway", dial_code: "+47", code: "NO", emoji: "🇳🇴" },
    OM: { name: "Oman", dial_code: "+968", code: "OM", emoji: "🇴🇲" },
    PK: { name: "Pakistan", dial_code: "+92", code: "PK", emoji: "🇵🇰" },
    PW: { name: "Palau", dial_code: "+680", code: "PW", emoji: "🇵🇼" },
    PS: {
      name: "Palestinian Territory, Occupied",
      dial_code: "+970",
      code: "PS",
      emoji: "🇵🇸"
    },
    PA: { name: "Panama", dial_code: "+507", code: "PA", emoji: "🇵🇦" },
    PG: {
      name: "Papua New Guinea",
      dial_code: "+675",
      code: "PG",
      emoji: "🇵🇬"
    },
    PY: { name: "Paraguay", dial_code: "+595", code: "PY", emoji: "🇵🇾" },
    PE: { name: "Peru", dial_code: "+51", code: "PE", emoji: "🇵🇪" },
    PH: { name: "Philippines", dial_code: "+63", code: "PH", emoji: "🇵🇭" },
    PN: { name: "Pitcairn", dial_code: "+872", code: "PN", emoji: "🇵🇳" },
    PL: { name: "Poland", dial_code: "+48", code: "PL", emoji: "🇵🇱" },
    PT: { name: "Portugal", dial_code: "+351", code: "PT", emoji: "🇵🇹" },
    PR: { name: "Puerto Rico", dial_code: "+1939", code: "PR", emoji: "🇵🇷" },
    QA: { name: "Qatar", dial_code: "+974", code: "QA", emoji: "🇶🇦" },
    RO: { name: "Romania", dial_code: "+40", code: "RO", emoji: "🇷🇴" },
    RU: { name: "Russia", dial_code: "+7", code: "RU", emoji: "🇷🇺" },
    RW: { name: "Rwanda", dial_code: "+250", code: "RW", emoji: "🇷🇼" },
    RE: { name: "Reunion", dial_code: "+262", code: "RE", emoji: "🇷🇪" },
    BL: {
      name: "Saint Barthelemy",
      dial_code: "+590",
      code: "BL",
      emoji: "🇧🇱"
    },
    SH: {
      name: "Saint Helena, Ascension and Tristan Da Cunha",
      dial_code: "+290",
      code: "SH",
      emoji: "🇸🇭"
    },
    KN: {
      name: "Saint Kitts and Nevis",
      dial_code: "+1869",
      code: "KN",
      emoji: "🇰🇳"
    },
    LC: { name: "Saint Lucia", dial_code: "+1758", code: "LC", emoji: "🇱🇨" },
    MF: { name: "Saint Martin", dial_code: "+590", code: "MF", emoji: "🇫🇷" },
    PM: {
      name: "Saint Pierre and Miquelon",
      dial_code: "+508",
      code: "PM",
      emoji: "🇵🇲"
    },
    VC: {
      name: "Saint Vincent and the Grenadines",
      dial_code: "+1784",
      code: "VC",
      emoji: "🇻🇨"
    },
    WS: { name: "Samoa", dial_code: "+685", code: "WS", emoji: "🇼🇸" },
    SM: { name: "San Marino", dial_code: "+378", code: "SM", emoji: "🇸🇲" },
    ST: {
      name: "Sao Tome and Principe",
      dial_code: "+239",
      code: "ST",
      emoji: "🇸🇹"
    },
    SA: { name: "Saudi Arabia", dial_code: "+966", code: "SA", emoji: "🇸🇦" },
    SN: { name: "Senegal", dial_code: "+221", code: "SN", emoji: "🇸🇳" },
    RS: { name: "Serbia", dial_code: "+381", code: "RS", emoji: "🇷🇸" },
    SC: { name: "Seychelles", dial_code: "+248", code: "SC", emoji: "🇸🇨" },
    SL: { name: "Sierra Leone", dial_code: "+232", code: "SL", emoji: "🇸🇱" },
    SG: { name: "Singapore", dial_code: "+65", code: "SG", emoji: "🇸🇬" },
    SK: { name: "Slovakia", dial_code: "+421", code: "SK", emoji: "🇸🇰" },
    SI: { name: "Slovenia", dial_code: "+386", code: "SI", emoji: "🇸🇮" },
    SB: { name: "Solomon Islands", dial_code: "+677", code: "SB", emoji: "🇸🇧" },
    SO: { name: "Somalia", dial_code: "+252", code: "SO", emoji: "🇸🇴" },
    ZA: { name: "South Africa", dial_code: "+27", code: "ZA", emoji: "🇿🇦" },
    SS: { name: "South Sudan", dial_code: "+211", code: "SS", emoji: "🇸🇸" },
    GS: {
      name: "South Georgia and the South Sandwich Islands",
      dial_code: "+500",
      code: "GS",
      emoji: "🇬🇸"
    },
    ES: { name: "Spain", dial_code: "+34", code: "ES", emoji: "🇪🇸" },
    LK: { name: "Sri Lanka", dial_code: "+94", code: "LK", emoji: "🇱🇰" },
    SD: { name: "Sudan", dial_code: "+249", code: "SD", emoji: "🇸🇩" },
    SR: { name: "Suriname", dial_code: "+597", code: "SR", emoji: "🇸🇷" },
    SJ: {
      name: "Svalbard and Jan Mayen",
      dial_code: "+47",
      code: "SJ",
      emoji: "🇳🇴"
    },
    SZ: { name: "Swaziland", dial_code: "+268", code: "SZ", emoji: "🇸🇿" },
    SE: { name: "Sweden", dial_code: "+46", code: "SE", emoji: "🇸🇪" },
    CH: { name: "Switzerland", dial_code: "+41", code: "CH", emoji: "🇨🇭" },
    SY: {
      name: "Syrian Arab Republic",
      dial_code: "+963",
      code: "SY",
      emoji: "🇸🇾"
    },
    TW: { name: "Taiwan", dial_code: "+886", code: "TW", emoji: "🇹🇼" },
    TJ: { name: "Tajikistan", dial_code: "+992", code: "TJ", emoji: "🇹🇯" },
    TZ: {
      name: "Tanzania, United Republic of Tanzania",
      dial_code: "+255",
      code: "TZ",
      emoji: "🇹🇿"
    },
    TH: { name: "Thailand", dial_code: "+66", code: "TH", emoji: "🇹🇭" },
    TL: { name: "Timor-Leste", dial_code: "+670", code: "TL", emoji: "🇹🇱" },
    TG: { name: "Togo", dial_code: "+228", code: "TG", emoji: "🇹🇬" },
    TK: { name: "Tokelau", dial_code: "+690", code: "TK", emoji: "🇹🇰" },
    TO: { name: "Tonga", dial_code: "+676", code: "TO", emoji: "🇹🇴" },
    TT: {
      name: "Trinidad and Tobago",
      dial_code: "+1868",
      code: "TT",
      emoji: "🇹🇹"
    },
    TN: { name: "Tunisia", dial_code: "+216", code: "TN", emoji: "🇹🇳" },
    TR: { name: "Turkey", dial_code: "+90", code: "TR", emoji: "🇹🇷" },
    TM: { name: "Turkmenistan", dial_code: "+993", code: "TM", emoji: "🇹🇲" },
    TC: {
      name: "Turks and Caicos Islands",
      dial_code: "+1649",
      code: "TC",
      emoji: "🇹🇨"
    },
    TV: { name: "Tuvalu", dial_code: "+688", code: "TV", emoji: "🇹🇻" },
    UG: { name: "Uganda", dial_code: "+256", code: "UG", emoji: "🇺🇬" },
    UA: { name: "Ukraine", dial_code: "+380", code: "UA", emoji: "🇺🇦" },
    AE: {
      name: "United Arab Emirates",
      dial_code: "+971",
      code: "AE",
      emoji: "🇦🇪"
    },
    UK: { name: "United Kingdom", dial_code: "+44", code: "UK", emoji: "🇬🇧" },
    US: { name: "United States", dial_code: "+1", code: "US", emoji: "🇺🇸" },
    UY: { name: "Uruguay", dial_code: "+598", code: "UY", emoji: "🇺🇾" },
    UZ: { name: "Uzbekistan", dial_code: "+998", code: "UZ", emoji: "🇺🇿" },
    VU: { name: "Vanuatu", dial_code: "+678", code: "VU", emoji: "🇻🇺" },
    VE: {
      name: "Venezuela, Bolivarian Republic of Venezuela",
      dial_code: "+58",
      code: "VE",
      emoji: "🇻🇪"
    },
    VN: { name: "Vietnam", dial_code: "+84", code: "VN", emoji: "🇻🇳" },
    VG: {
      name: "Virgin Islands, British",
      dial_code: "+1284",
      code: "VG",
      emoji: "🇻🇬"
    },
    VI: {
      name: "Virgin Islands, U.S.",
      dial_code: "+1340",
      code: "VI",
      emoji: "🇻🇮"
    },
    WF: {
      name: "Wallis and Futuna",
      dial_code: "+681",
      code: "WF",
      emoji: "🇼🇫"
    },
    YE: { name: "Yemen", dial_code: "+967", code: "YE", emoji: "🇾🇪" },
    ZM: { name: "Zambia", dial_code: "+260", code: "ZM", emoji: "🇿🇲" },
    ZW: { name: "Zimbabwe", dial_code: "+263", code: "ZW", emoji: "🇿🇼" }
  }
];

export default countryCodesIndexed;
